In [28]:
import pandas as pd
import ast

In [125]:
df = pd.read_csv('pre_cleaned_output.csv')
df.head()

,business_name,category,ratings,years_open,phone_number,full_address,street_address,city,price
0,"('The Spinnaker - Sausalito', 0)","(['Restaurants', 'Banquet Halls & Reception Fa...","('{""rating"":""4.0"",""count"":""17""}', 0)","('63', 0)","('(510) 768-8354', 0)","('100 Spinnaker Dr, Sausalito, CA 94965', 0)","('3211 Grand Ave', 0)","('Oakland, CA 94610', 0)","('$', 0)"
1,"('Yang Chow Restaurant', 1)","(['Restaurants', 'Asian Restaurants', 'Take Ou...","('{""rating"":""4.5"",""count"":""8""}', 1)","('3', 1)","('(510) 465-4629', 1)","('100 Spinnaker Dr, Sausalito, CA 94965', 1)","('3232 Grand Ave.', 1)","('Oakland, CA 94610', 1)","('$', 1)"
2,"('Hunan Village', 2)","(['Restaurants', 'Asian Restaurants', 'Take Ou...","(""{'rating': '', 'count': ''}"", 2)","('48', 2)","('(510) 444-3456', 2)","('7986 Tesla Rd, Livermore, CA 94550', 2)","('2 Broadway', 2)","('Oakland, CA 94607', 2)","('$$', 2)"
3,"(""Scott's Seafood Jack London Square"", 3)","(['Restaurants', 'Wedding Supplies & Services'...","('{""rating"":""4.0"",""count"":""54""}', 3)","('14', 3)","('(510) 654-2681', 3)","('601 Main St, Martinez, CA 94553', 3)","('4218 Piedmont Ave', 3)","('Oakland, CA 94611', 3)","('$$', 3)"
4,"('Xyclo Restaurant', 4)","(['Restaurants', 'Vietnamese Restaurants', 'Fa...","('{""rating"":""4.0"",""count"":""101""}', 4)","('37', 4)","('(510) 652-3676', 4)","('601 Main St, Martinez, CA 94553', 4)","('4293 Piedmont Ave', 4)","('Oakland, CA 94611', 4)","('$$', 4)"

In [126]:
for column in df.columns:
    df[column] = df[column].apply(ast.literal_eval).str[0]

df.head()

,business_name,category,ratings,years_open,phone_number,full_address,street_address,city,price
0,The Spinnaker - Sausalito,"[Restaurants, Banquet Halls & Reception Facili...","{""rating"":""4.0"",""count"":""17""}",63,(510) 768-8354,"100 Spinnaker Dr, Sausalito, CA 94965",3211 Grand Ave,"Oakland, CA 94610",$
1,Yang Chow Restaurant,"[Restaurants, Asian Restaurants, Take Out Rest...","{""rating"":""4.5"",""count"":""8""}",3,(510) 465-4629,"100 Spinnaker Dr, Sausalito, CA 94965",3232 Grand Ave.,"Oakland, CA 94610",$
2,Hunan Village,"[Restaurants, Asian Restaurants, Take Out Rest...","{'rating': '', 'count': ''}",48,(510) 444-3456,"7986 Tesla Rd, Livermore, CA 94550",2 Broadway,"Oakland, CA 94607",$$
3,Scott's Seafood Jack London Square,"[Restaurants, Wedding Supplies & Services, Ame...","{""rating"":""4.0"",""count"":""54""}",14,(510) 654-2681,"601 Main St, Martinez, CA 94553",4218 Piedmont Ave,"Oakland, CA 94611",$$
4,Xyclo Restaurant,"[Restaurants, Vietnamese Restaurants, Family S...","{""rating"":""4.0"",""count"":""101""}",37,(510) 652-3676,"601 Main St, Martinez, CA 94553",4293 Piedmont Ave,"Oakland, CA 94611",$$

In [127]:
def safe_literal_eval(s):
    try:
        return ast.literal_eval(s)
    except (ValueError, SyntaxError):
        return {"rating":None,"count":None}

df['ratings'] = df['ratings'].apply(safe_literal_eval)

In [128]:
df['stars'] = df['ratings'].str["rating"]
df['num_reviews'] = df['ratings'].str["count"]
df.head()

,business_name,category,ratings,years_open,phone_number,full_address,street_address,city,price,stars,num_reviews
0,The Spinnaker - Sausalito,"[Restaurants, Banquet Halls & Reception Facili...","{'rating': '4.0', 'count': '17'}",63,(510) 768-8354,"100 Spinnaker Dr, Sausalito, CA 94965",3211 Grand Ave,"Oakland, CA 94610",$,4.0,17
1,Yang Chow Restaurant,"[Restaurants, Asian Restaurants, Take Out Rest...","{'rating': '4.5', 'count': '8'}",3,(510) 465-4629,"100 Spinnaker Dr, Sausalito, CA 94965",3232 Grand Ave.,"Oakland, CA 94610",$,4.5,8
2,Hunan Village,"[Restaurants, Asian Restaurants, Take Out Rest...","{'rating': '', 'count': ''}",48,(510) 444-3456,"7986 Tesla Rd, Livermore, CA 94550",2 Broadway,"Oakland, CA 94607",$$,,
3,Scott's Seafood Jack London Square,"[Restaurants, Wedding Supplies & Services, Ame...","{'rating': '4.0', 'count': '54'}",14,(510) 654-2681,"601 Main St, Martinez, CA 94553",4218 Piedmont Ave,"Oakland, CA 94611",$$,4.0,54
4,Xyclo Restaurant,"[Restaurants, Vietnamese Restaurants, Family S...","{'rating': '4.0', 'count': '101'}",37,(510) 652-3676,"601 Main St, Martinez, CA 94553",4293 Piedmont Ave,"Oakland, CA 94611",$$,4.0,101

In [133]:
df['years_open'] = df['years_open'].fillna(0).astype(int)
df['stars'] = df['stars'].fillna(0.0).replace("",0.0).astype(float)
df['num_reviews'] = df['num_reviews'].fillna(0).replace("",0).astype(int)

df.head()

,business_name,category,ratings,years_open,phone_number,full_address,street_address,city,price,stars,num_reviews
0,The Spinnaker - Sausalito,"[Restaurants, Banquet Halls & Reception Facili...","{'rating': '4.0', 'count': '17'}",63,(510) 768-8354,"100 Spinnaker Dr, Sausalito, CA 94965",3211 Grand Ave,"Oakland, CA 94610",$,4.0,17
1,Yang Chow Restaurant,"[Restaurants, Asian Restaurants, Take Out Rest...","{'rating': '4.5', 'count': '8'}",3,(510) 465-4629,"100 Spinnaker Dr, Sausalito, CA 94965",3232 Grand Ave.,"Oakland, CA 94610",$,4.5,8
2,Hunan Village,"[Restaurants, Asian Restaurants, Take Out Rest...","{'rating': '', 'count': ''}",48,(510) 444-3456,"7986 Tesla Rd, Livermore, CA 94550",2 Broadway,"Oakland, CA 94607",$$,0.0,0
3,Scott's Seafood Jack London Square,"[Restaurants, Wedding Supplies & Services, Ame...","{'rating': '4.0', 'count': '54'}",14,(510) 654-2681,"601 Main St, Martinez, CA 94553",4218 Piedmont Ave,"Oakland, CA 94611",$$,4.0,54
4,Xyclo Restaurant,"[Restaurants, Vietnamese Restaurants, Family S...","{'rating': '4.0', 'count': '101'}",37,(510) 652-3676,"601 Main St, Martinez, CA 94553",4293 Piedmont Ave,"Oakland, CA 94611",$$,4.0,101